import os

AZURE_STORAGE_CONNECTION_STRING = os.environ['AZURE_IMAGE_STORAGE_CONNECTION_STRING']
CONTAINER_NAME = os.environ.get('AZURE_IMAGE_STORAGE_CONTAINER_NAME', 'random-images')
ROTATE_ANGLE_DEFAULT = 90
